swagger: "2.0"
info:
  version: 1.0.0
  title: noteflow
  description: cnpmm project
basePath: /api/v1
tags:
  - name: Users
    description: Endpoints for managing users
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  User:
    type: object
    title: user
    required:
      - username
      - email
    properties:
      username:
        type: string
        example: johndoe
      email:
        type: string
        example: johndoe@example.com
      password:
        type: string
        example: strongpassword123

paths:
  /users:
    post:
      tags:
        - Users
      description: Create a new user
      parameters:
        - email: email@gmail.com
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: User created successfully
        400:
          description: Invalid input

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
